### PR TITLE
a little jade automation

### PR DESCRIPTION
**Pull request by ilkosta**
inserted:
- JadeMaker called by `development.coffee` with the same output of `brunch watch --server`
- the coffeelint-brunch plugin

### CODE REVIEW

**Comment by kylefinley** [comment]
@ilkosta Thank you for putting this together!

coffeelint-brunch looks nice, I definitely would like to incorporate it.

Would it be possible to make JadeMake a brunch plugin? I need to study up on how to create plugins, but it seems like this is something that will be useful in many different projects. I asked Paul Miller about this and he said that there was a `plugin.onCompile` API hook that could be used for this.

Also, what do you think about compiling the jade => html in the `_public` / output folder instead of the `app/assets` folder?

And, could you please add a pull request with your information added to the `AUTHORS.md` and `CONTRIBUTORS.md`

Thanks again for putting this together. Let me know what you think.

-Kyle

**Comment by ilkosta** [comment]
2012/8/22 Kyle Finley notifications@github.com

> @ilkosta https://github.com/ilkosta Thank you for putting this together!
> 
> Would it be possible to make JadeMake a brunch plugin? I need to study up
> on how to create plugins, but it seems like this is something that will be
> useful in many different projects. I asked Paul Miller about this and he
> said that there was a plugin.onCompile API hook that could be used for
> this.

really interesting, I'm a newbie on brunch but I will check.

> Also, what do you think about compiling the jade => html in the _public /
> output folder instead of the app/assets folder?
> 
> right, I forgot to adjust the parameters of jade to tell it to save in
> _public
> 
> And, could you please add a pull request with your information added to
> the AUTHORS.md and CONTRIBUTORS.md
> 
>  I will investigate the possibility to make it a plugin and I hope to soon
> make a better pull.

## Thank you,

Costantino Giuliodori

**Comment by vendethiel** [comment]
amazing :) !

**Comment by ilkosta** [comment]
I've created the [static-jade-brunch](https://github.com/ilkosta/static-jade-brunch) that must co-exists with the [jade-brunch](https://github.com/brunch/jade-brunch) plugin and It work nicely inside angular-brunch-seed .

The only suggested chages are to add in the `config.coffee`:

``` coffeescript
templates:
      joinTo:
        'js/templates.js': /.+\.jade$/
```

For convenience I changed the wrapper to filter only the jade file (as suggested by @paulmillr) with something like:

``` coffeescript
wrapper: (path, data) ->
      if /.+\.jade$/.test path
        """
        (function() {
        }).call(this);\n\n
        """
```

@hekki provided [some changes to angular-brunch-seed](https://github.com/heikki/angular-brunch-seed/compare/static-jade-brunch) to make it use static-jade-brunch. 

Really thanks to @paulmillr and @heikki for fix and hints.

**Comment by kylefinley** [comment]
@ilkosta Excellent work!! It looks great. Could you send me a pull request with your information added to CONTRIBUTORS.md and AUTHORS.md files?

@heikki would it be allright if I merged your `static-brunch-seed` branch into master? If so could you add your information to the CONTRIBUTORS.md and AUTHORS.md files and I'll pull those changes in at the same time.

Thank you everyone for putting this together, it really helps simplify the build process.

**Comment by heikki** [comment]
Pull request ready. Thanks on my behalf too :). Good stuff.

**Comment by kylefinley** [comment]
Closed by [Pull #11](https://github.com/scotch/angular-brunch-seed/pull/11)

**Pull request closed without merging**
