### PR TITLE
Update Angular JS to 1.0.3 Issue #35

### PR DESCRIPTION
**Pull request by Hoverbear**
Updated Bootstrap as well (Take a look at this commit, 3 new files were created and I've no idea why they weren't there previously.)

### CODE REVIEW

**Comment by kylefinley** [comment]
Looks Good! Thank you for doing this.

The reason you had a different number of files for bootstrap, was because I've made some customizations to allow for themes. I'll pull in the jQuery and AngularJS, and modify the Bootstrap commit later today.

Thanks again.

**Comment by Hoverbear** [comment]
Happy to help. I'm trying to wrap my head around brunch, figured this is a good way to get started.

**Comment by kylefinley** [comment]
@Hoverbear, 

I finally got this merged sorry for the delay. 

When you get a chance could you please send me a pull request with you information added to the CONTRIBUTORS.md and AUTHOR.md files?

Thank you,

Kyle

**Comment by Hoverbear** [comment]
I wouldn't really call it a contribution. :-P Don't worry about it.

**Pull request merged**
